#if !defined(BL_CONFIG_H_)
#define BL_CONFIG_H_

#include <stdbool.h>
#include "hal/gpio.h"
#include "hal/sercom_usart.h"

#define COMM_DEFAULT_SERCOM SERCOM3
#define COMM_DEFAULT_BAUDRATE 19200
#define COMM_DEFAULT_ONE_WIRE false

#define COMM_DEFAULT_TX_PORT PORT_GROUP_A
#define COMM_DEFAULT_TX_PIN 24
#define COMM_DEFAULT_TX_PAD SERCOM_USART_TX_PAD2

#define COMM_DEFAULT_RX_PORT PORT_GROUP_A
#define COMM_DEFAULT_RX_PIN 25
#define COMM_DEFAULT_RX_PAD SERCOM_USART_RX_PAD3

#define COMM_DEFAULT_TXE_PORT 0xFF
#define COMM_DEFAULT_TXE_PIN 0xFF

#define COMM_DEFAULT_CS_PORT 0xFF
#define COMM_DEFAULT_CS_PIN 0xFF

#endif // BL_CONFIG_H_
