name: CI

on:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: ghcr.io/c4deszes/arm-gcc-docker:v1.2.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        run: cmake --preset=armgcc-debug-unix .

      - name: Build
        run: cmake --build --preset=build-app-armgcc-debug-unix

      # TODO: archive build
      - name: Archive documentation
        uses: actions/upload-artifact@v4
        with:
          name: binary
          path: |
            _build/armgcc-debug-unix/bootloader.*
          if-no-files-found: error

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: python -m pip install -r docs/requirements.txt

      - name: Intall draw.io dependencies
        run: |
          wget -O drawio.deb https://github.com/jgraph/drawio-desktop/releases/download/v20.6.2/drawio-amd64-20.6.2.deb
          sudo apt install xvfb ./drawio.deb

      - name: Build documentation
        run: python -m sphinx -b html -E docs docs/_build

      - name: Archive documentation
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: |
            docs/_build
          if-no-files-found: error
