name: CI

on:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: ghcr.io/c4deszes/arm-gcc-docker:v1.1.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        run: cmake --preset=armgcc-debug-unix .

      - name: Build
        run: cmake --build --preset=build-app-armgcc-debug-unix

      # TODO: archive build
